### ISSUE TITLE
C#调用时的内存访问错误

### ISSUE THREAD

**Issue by Junyi-99** [CaoMengLong/PrinterMonitorLib#2]
按照[Wiki中](https://github.com/CaoMengLong/PrinterMonitorLib/wiki/%E5%A6%82%E4%BD%95%E5%9C%A8C%23%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-PrinterMonitorLib)所示代码

编译运行会有内存错误

**Comment by Junyi-99** [comment]
尝试读取或写入受保护的内存。这通常指示其他内存已损坏

**Comment by Lino-H** [comment]
DLLImport 一直报找不到指定模块
